Add ovpn_genclient script for client certificate generation

diff --git a/rootfs/usr/local/bin/ovpn_getclient b/rootfs/usr/local/bin/ovpn_getclient
--- a/rootfs/usr/local/bin/ovpn_getclient
+++ b/rootfs/usr/local/bin/ovpn_getclient
@@ -24,10 +24,11 @@ if [ -z "$EASYRSA_PKI" ]; then
 fi
 
 cn="$1"
+
 mode="$2"
 
-if [ ! -f "$EASYRSA_PKI/private/${cn}.key" ]; then
-    echo "Unable to find \"${cn}\", please try again or generate the key first" >&2
+if [ ! -f "$EASYRSA_PKI/private/$cn.key" ]; then
+    echo "Unable to find \"$cn\", please try again or generate the key first" >&2
     exit 1
 fi
 
@@ -125,10 +126,11 @@ case "$mode" in
 
         get_client_config "$mode" > "$dir/${cn}.ovpn"
 
-        cp "$EASYRSA_PKI/private/${cn}.key" "$dir/${cn}.key"
         cp "$EASYRSA_PKI/ca.crt" "$dir/ca.crt"
-        cp "$EASYRSA_PKI/issued/${cn}.crt" "$dir/${cn}.crt"
         cp "$EASYRSA_PKI/ta.key" "$dir/ta.key"
+
+        cp "$EASYRSA_PKI/private/$cn.key" "$dir/$cn.key"
+        cp "$EASYRSA_PKI/issued/$cn.crt" "$dir/$cn.crt"
         ;;
 
     "" | "combined")
@@ -137,7 +139,7 @@ case "$mode" in
 
     "combined-save")
         mkdir -p "$dir"
-        get_client_config "combined" > "$dir/${cn}-combined.ovpn"
+        get_client_config "combined" > "$dir/$cn-combined.ovpn"
         ;;
 
     *)
