Refactor OpenVPN scripts: streamline variable usage, improve readability, and enhance error handling

diff --git a/rootfs/usr/local/bin/ovpn_revokeclient b/rootfs/usr/local/bin/ovpn_revokeclient
--- a/rootfs/usr/local/bin/ovpn_revokeclient
+++ b/rootfs/usr/local/bin/ovpn_revokeclient
@@ -25,16 +25,20 @@ fi
 
 cn="$1"
 
-if [ ! -f "$EASYRSA_PKI/private/${cn}.key" ]; then
-    echo "Unable to find \"${cn}\", please try again or generate the key first" >&2
+if [ ! -f "$EASYRSA_PKI/private/$cn.key" ]; then
+    echo "Unable to find \"$cn\", please try again or generate the key first" >&2
     exit 1
 fi
 
 revoke_client_certificate(){
     easyrsa revoke "$1"
+
     echo "Generating the Certificate Revocation List :"
+
     easyrsa gen-crl
+
     cp -f "$EASYRSA_PKI/crl.pem" "$OPENVPN/crl.pem"
+
     chmod 644 "$OPENVPN/crl.pem"
 }
 
